In [3]:
import numpy as np

In [223]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

1. How many negative numbers are there?

In [226]:
np.count_nonzero(a < 0)

4

2. How many positive numbers are there?

In [219]:
np.count_nonzero(a > 0)


array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

3. How many even positive numbers are there?

In [228]:
np.count_nonzero((a > 0) & (a % 2 == 0))

3

4. If you were to add 3 to each data point, how many positive numbers would there be?

In [43]:
b = (a + 3)
mask = (b > 0)
len(b[mask])

10

5. If you squared each number, what would the new mean and standard deviation be?

In [230]:
b = a ** 2
b.mean()
b.std()


144.0243035046516

6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [49]:
a.mean()

3.0

In [234]:
b = a - a.mean()
b
# b.mean()

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

7. Calculate the z-score for each data point. Recall that the z-score is given by:

In [238]:
z = (a - a.mean()) / a.std()
z

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

8. 

In [60]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#Use python's built in functionality/operators to determine the following:

Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [62]:
sum_of_a = sum(a)
sum_of_a

55

 Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [65]:
min_of_a = min(a)
min_of_a

1

 Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [67]:
max_of_a = max(a)
max_of_a

10

 Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [73]:
mean_of_a = sum_of_a / len(a)
mean_of_a

5.5

Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [76]:
product_of_a = 1
for num in a:
    product_of_a *= num 
product_of_a    

3628800

Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [78]:
squares_of_a = []
for num in a:
    squares_of_a.append(num**2)
squares_of_a    

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

 Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [79]:
odds_in_a = []
for num in a:
    if num % 2 != 0:
        odds_in_a.append(num)
odds_in_a        

[1, 3, 5, 7, 9]

 Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [80]:
evens_in_a = []
for num in a:
    if num % 2 == 0:
        evens_in_a.append(num)
evens_in_a        

[2, 4, 6, 8, 10]

 What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
 Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.



In [99]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [84]:
np.sum(b)

33

In [86]:
np.min(b)

3

In [87]:
np.max(b)

8

In [89]:
np.mean(b)

5.5

In [90]:
np.product(b)

20160

In [91]:
np.square(b)

array([[ 9, 16, 25],
       [36, 49, 64]])

#Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

In [103]:
b = np.array(b)
b.sum()

33

 Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) 

In [114]:
min_of_b = b.min()
min_of_b

3

Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [115]:
max_of_b = np.max(b)
max_of_b

8

#Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [122]:
mean_of_b = b.sum()
mean_of_b

33

 Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [124]:
product_of_b = np.product(b)
product_of_b

20160

Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [126]:
squares_of_b = np.square(b)
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

 Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [135]:
mask = (b % 2 != 0)

b[mask]


array([3, 5, 7])

Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

In [139]:
mask = (b % 2 == 0)
b[mask]


array([4, 6, 8])

 Exercise 9 - print out the shape of the array b.

In [143]:
b.shape


(2, 3)

 Exercise 10 - transpose the array b.

In [146]:
b.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

 Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [148]:
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

 Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [149]:
b.reshape(6, 1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

### Setup 3


In [150]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]



### Exercise 1 - Find the min, max, sum, and product of c.

In [154]:
c = np.array(c)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [155]:
c.min()

1

In [156]:
c.max()

9

In [157]:
c.sum()

45

In [160]:
np.product(c)

362880

 Exercise 2 - Determine the standard deviation of c.

In [162]:
np.std(c)

2.581988897471611

Exercise 3 - Determine the variance of c.

In [163]:
np.var(c)

6.666666666666667

 Exercise 4 - Print out the shape of the array c

In [164]:
print(c.shape)

(3, 3)


 Exercise 5 - Transpose c and print out transposed result.

In [165]:
print(c.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


 Exercise 6 - Get the dot product of the array c with c. 

In [168]:
np.dot(c, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

 Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [239]:
((c * np.transpose(c))).sum()

261

 Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [184]:
np.product(c * np.transpose(c))

131681894400

### Setup 4

In [185]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [210]:
d = np.array(d)

 Exercise 1 - Find the sine of all the numbers in d

In [192]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

Exercise 2 - Find the cosine of all the numbers in d

In [193]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

Exercise 3 - Find the tangent of all the numbers in d

In [194]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

 Exercise 4 - Find all the negative numbers in d

In [243]:
d [d < 0]

array([-90, -30, -45, -45])

Exercise 5 - Find all the positive numbers in d

In [242]:
d [d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

 Exercise 6 - Return an array of only the unique numbers in d.

In [197]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

 Exercise 7 - Determine how many unique numbers there are in d.

In [200]:
len(np.unique(d))

11

 Exercise 8 - Print out the shape of d.

In [204]:
print(np.shape(d))

(3, 6)


Exercise 9 - Transpose and then print out the shape of d.

In [247]:
d.T.shape

(6, 3)

Exercise 10 - Reshape d into an array of 9 x 2

In [211]:
d.reshape(9, 2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])